//Department Actions
export const REGISTER_DEPARTMENT = "REGISTER_DEPARTMENT";
export const REGISTER_DEPARTMENT_SUCCESS = "REGISTER_DEPARTMENT_SUCCESS";
export const REGISTER_DEPARTMENT_FAIL = "REGISTER_DEPARTMENT_FAIL";
export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const GET_DEPARTMENT = "GET_DEPARTMENT";

export const GET_STRUCTURE = "GET_STRUCTURE";
export const DEPARTMENT_ERROR = "DEPARTMENT_ERROR";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
